#%RAML 1.0
title: products-api
baseUri: http://localhost:8081/products

/products:
  get:
    description: To get products
    responses:
      200:
        body:
          application/json:
            example:
              {
                "productID": 123654,
                "productName": "Mule deployment",
                "productProvider": "Test",
                "productDescription": "Check ways of mule deployment."
              }  

