#%RAML 1.0
title: products-sapi
version: v1
baseUri: http://localhost:8081/

types: 
  product: !include dataType/ProductsDataType.raml 
  

/products:
  get:
    description: "To get all products details"
    responses:
      200:
        body:
          application/json:
            type: product[]
            examples:
                {
                  id:1,
                  name:"Coffee Mug - Relax",
                  description:"Do you love mathematics? ",
                  unit_price:10.22,
                  active:"A",
                  category:"Coffee Mugs",
                  categoryId:2
                }
  
  post:
  
  
  /{ID}:
    get:
      description: "To get products details by passing ID in URI parameter"
      responses:
        200:
          body:
            application/json:
              type: product
              examples:
                  {
                    id:1,
                    name:"Coffee Mug - Relax",
                    description:"Do you love mathematics? ",
                    unit_price:10.22,
                    active:"A",
                    category:"Coffee Mugs",
                    categoryId:2
                  }
    post:    
    delete:
    
    
    